//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyAspNetHost
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deelnemer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deelnemer()
        {
            this.PloegDeelnemer = new HashSet<PloegDeelnemer>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PersoonID { get; set; }
        public int Nummer { get; set; }

        [Newtonsoft.Json.JsonIgnoreAttribute]
        public virtual Persoon Persoon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Newtonsoft.Json.JsonIgnoreAttribute]
        public virtual ICollection<PloegDeelnemer> PloegDeelnemer { get; set; }
    }
}
