//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyAspNetHost
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Blok = new HashSet<Blok>();
        }
    
        public int Id { get; set; }
        public string EventGuid { get; set; }
        public string Afkorting { get; set; }
        public string Naam { get; set; }
        public Nullable<int> OrganisatorID { get; set; }
        public System.DateTime StartDatum { get; set; }
        public System.DateTime EindDatum { get; set; }
        public int Afstand { get; set; }
        public string Plaats { get; set; }
        public Nullable<int> LoginID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Newtonsoft.Json.JsonIgnoreAttribute]
        public virtual ICollection<Blok> Blok { get; set; }
        [Newtonsoft.Json.JsonIgnoreAttribute]
        public virtual Vereniging Vereniging { get; set; }
        [Newtonsoft.Json.JsonIgnoreAttribute]
        public virtual Login Login { get; set; }
    }
}
