//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyAspNetHost
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginToken
    {
        public int Id { get; set; }
        public System.Guid Token { get; set; }
        public Nullable<int> LoginID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string IPAdress { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
