//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyAspNetHost
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimechasersEntities : DbContext
    {
        public TimechasersEntities()
            : base("name=TimechasersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blok> Blok { get; set; }
        public virtual DbSet<Deelnemer> Deelnemer { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Persoon> Persoon { get; set; }
        public virtual DbSet<Ploeg> Ploeg { get; set; }
        public virtual DbSet<PloegDeelnemer> PloegDeelnemer { get; set; }
        public virtual DbSet<Tijd> Tijd { get; set; }
        public virtual DbSet<Veld> Veld { get; set; }
        public virtual DbSet<Vereniging> Vereniging { get; set; }
        public virtual DbSet<LoginToken> LoginToken { get; set; }
    }
}
