//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyAspNetHost
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persoon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persoon()
        {
            this.Deelnemer = new HashSet<Deelnemer>();
        }
    
        public int Id { get; set; }
        public string Naam { get; set; }
        public Nullable<int> VerenigingID { get; set; }
        public System.DateTime GeboorteDatum { get; set; }
        public string KNRBID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Newtonsoft.Json.JsonIgnoreAttribute]
        public virtual ICollection<Deelnemer> Deelnemer { get; set; }
        [Newtonsoft.Json.JsonIgnoreAttribute]
        public virtual Vereniging Vereniging { get; set; }
    }
}
