//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyAspNetHost
{
    using System;
    using System.Collections.Generic;
    
    public partial class PloegDeelnemer
    {
        public int Id { get; set; }
        public Nullable<int> DeelnemerID { get; set; }
        public Nullable<int> PloegID { get; set; }

        [Newtonsoft.Json.JsonIgnoreAttribute]
        public virtual Deelnemer Deelnemer { get; set; }
        [Newtonsoft.Json.JsonIgnoreAttribute]
        public virtual Ploeg Ploeg { get; set; }
    }
}
