//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyAspNetHost
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veld
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Veld()
        {
            this.Ploeg = new HashSet<Ploeg>();
        }
    
        public int Id { get; set; }
        public string Afkorting { get; set; }
        public string ANaam { get; set; }
        public Nullable<int> BlokID { get; set; }

        [Newtonsoft.Json.JsonIgnoreAttribute]
        public virtual Blok Blok { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Newtonsoft.Json.JsonIgnoreAttribute]
        public virtual ICollection<Ploeg> Ploeg { get; set; }
    }
}
